# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-04 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='payment_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='avec',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='participant',
            name='comment',
            field=models.TextField(blank=True, default='none'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='diet',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
