# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-06 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190104_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
